application: libcoffeeblog
version: 1
runtime: python
api_version: 1

default_expiration: '3650d'

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  secure: optional
  login: admin

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /_ereporter/.*
  script: $PYTHON_LIB/google/appengine/ext/ereporter/report_generator.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/__init__.py
  login: admin
  
- url: /.*?/tasks/.*
  script: common/appenginepatch/main.py
  login: admin

- url: /.*
  script: common/appenginepatch/main.py
  secure: optional


inbound_services:
- xmpp_message
- mail


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$