application: libcoffeeblog
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: '3650d'

builtins:
- admin_redirect: on
- appstats: on
- deferred: on
- remote_api: on

libraries:
- name: django
  version: latest

inbound_services:
- xmpp_message
- mail
- warmup


handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /media
  static_dir: _generated_media
  secure: optional

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /LiveSearchSiteAuth.xml
  static_files: static/LiveSearchSiteAuth.xml
  upload: static/LiveSearchSiteAuth.xml

- url: /google83465fecfae4c3c3.html
  static_files: static/google83465fecfae4c3c3.html
  upload: static/google83465fecfae4c3c3.html
  
- url: /.*?/tasks/.*
  script: djangoappengine.main.application
  login: admin

- url: /.*
  script: djangoappengine.main.application
  secure: optional


skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
