application: libcoffeeblog-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "latest"
- name: markupsafe
  version: "latest"
- name: PIL
  version: "latest"
- name: lxml
  version: "latest"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /_gae_mini_profiler/static
  static_dir: flaskext/gae_mini_profiler/static

- url: /static/img/
  static_dir: static

- url: /static
  static_dir: static

- url: .*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^google$